import type { Metadata } from "next";
import "./globals.css";
import "primereact/resources/themes/lara-dark-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import { Player } from "@components/media/player/index";
import { Poppins } from "next/font/google";
import { Toaster } from "sonner";
import { CreatePlaylistDialog } from "@components/features/dialogs/CreatePlaylistDialog";
import { LikeHydrator } from "@components/hydrators/LikeHydrator";
import { getUserAvatar } from "@/actions/user";
import { PlaylistsHydrator } from "@components/hydrators/PlaylistsHidrator";
import { FollowHydrator } from "@components/hydrators/FollowHydrator";
import { UserAvatarHydrator } from "@/components/hydrators/UserAvatarHydrator";
import { getCollection } from "@/shared/server/user/user.service";
import { CollectionHydrator } from "@/components/hydrators/CollectionHydator";
import { getUserLikedTracks } from "@/actions/user/like";
import { getUserPlaylists } from "@/actions/user/playlist";
import { getUserArtistFollowingIds } from "@/actions/user/following";
import { InitPlayerHydrator } from "@/components/hydrators/InitPlayerHydrator";

export const metadata: Metadata = {
  title: "Mat Sound",
  description: "Generated by create next app",
};

const nunitoSans = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const likedTracks = getUserLikedTracks();
  const playlists = getUserPlaylists();
  const artistFolloingIds = getUserArtistFollowingIds();
  const userAvatarPromise = getUserAvatar();
  const collection = getCollection();
  return (
    <html lang="es" className={nunitoSans.className}>
      <body className="bg-background h-screen w-screen">
        <UserAvatarHydrator userAvatarPromise={userAvatarPromise} />
        <LikeHydrator likedTracks={likedTracks} />
        <PlaylistsHydrator playlists={playlists} />
        <FollowHydrator artistFolloingIds={artistFolloingIds} />
        <CollectionHydrator collection={collection} />
        <InitPlayerHydrator />
        {children}
        <Player />
        <Toaster theme="dark" richColors className="!h-6 " position="top-center" />
        <CreatePlaylistDialog />
      </body>
    </html>
  );
}
