import type { Metadata } from "next";
import "./globals.css";
import "primereact/resources/themes/lara-dark-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import Player from "@/components/Media/Player";
import { Poppins } from "next/font/google";

export const metadata: Metadata = {
  title: "Mat Sound",
  description: "Generated by create next app",
};

const nunitoSans = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es" className={nunitoSans.className}>
      <body className="bg-background h-screen w-screen">
        {children}
        <Player />
      </body>
    </html>
  );
}
